apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .serviceName }}
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/{{ .githubOrg }}/{{ .serviceName }}-chart.git
        revision: HEAD
        directories:
          - path: environments/*
  template:
    metadata:
      name: "{{ .serviceName }}-{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/{{ .githubOrg }}/{{ .serviceName }}-chart.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: "{{ path.basename }}"
        namespace: {{ .projectName }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
