apiVersion: codepusher.io/v1alpha1
kind: template
metadata:
  name: java-springboot-service
  displayName: Scaffold a new Java Spring Boot service
  description: Quickly set up a new Java Spring Boot project with this template.
  tags:
    - java
    - springboot
    - service
    - api
spec:
  templateUrl: "https://github.com/codepusher-platform/codepusher-blueprints-aws/blob/main/github/java/java-springboot/template"  # Replace with your actual template URL
  provider: github
  owner: codepusher-team
  type: service
  language: java
  engine:
    type: github
    version: "1.0.0"
  steps:
    - title: Basic Information
      properties:
        serviceName:
          title: Service Name (K8s)
          type: string
          description: "Unique name for your Spring Boot service within Kubernetes (e.g., 'my-springboot-app')."
        project:
          title: Project Name (GitHub)
          type: string
          description: "The name of your GitHub repository where your Spring Boot project's code resides."
        owner:
          title: Owner
          type: select
          items:
            type: list:team
        githubOrg:
          type: get:integration:githubOrg
          autofill: true
        dependencies:
          title: Dependencies
          type: array
          description: "Add any additional Spring Boot starters (e.g., 'spring-boot-starter-data-jpa', 'spring-boot-starter-web')." 
          items:
            type: string
