name: Apply ApplicationSet

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  apply-argo-applicationset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Update kubeconfig
        run: |
          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_ARGO }}

      - name: Apply
        run: kubectl apply -f ${{ github.workspace }}/argocd/applicationset.yaml
